apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml

images:
  - name: ghcr.io/REPLACE_ME/mealie-gkeep-sync
    newTag: 0.1.0
