apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-gkeep-sync-state
  labels:
    app.kubernetes.io/name: mealie-gkeep-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  # storageClassName: longhorn
