#!/usr/bin/env python3
"""One-time helper: turn a browser OAuth token into a Google master token.

Run this on your workstation, not in the cluster. The password-based master login that
older guides describe is unreliable now - Google flags it as suspicious and returns
BadAuthentication - so this uses the browser-assisted flow instead.

    1. In a browser signed in as the account that owns the Keep list, open:
           https://accounts.google.com/EmbeddedSetup
       (An "unsupported browser" page is fine; the cookie is still set. Accept the
       terms prompt if one appears.)

    2. Open DevTools -> Application -> Cookies -> https://accounts.google.com and copy
       the value of the `oauth_token` cookie. It starts with `oauth2_4/`.

    3. Run:
           python tools/get_master_token.py you@gmail.com

       and paste the cookie value when prompted.

The result starts with `aas_et/`. It is password-equivalent - full access to the Google
account, not just Keep - so put it straight into a Kubernetes Secret and never commit it.
It stays valid until you change the account password or revoke it at
https://myaccount.google.com/device-activity.
"""

from __future__ import annotations

import argparse
import getpass
import secrets
import sys

try:
    import gpsoauth
except ImportError:  # pragma: no cover - helper script
    print("gpsoauth is missing. Install this project first:", file=sys.stderr)
    print("    pip install -e .", file=sys.stderr)
    raise SystemExit(1) from None


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Exchange a browser oauth_token for a Google master token.",
        epilog="See the module docstring for how to obtain the oauth_token cookie.",
    )
    parser.add_argument("email", help="Google account email, e.g. you@gmail.com")
    parser.add_argument(
        "--android-id",
        default=secrets.token_hex(8),
        help="16-hex-digit device ID (a random one is generated by default).",
    )
    args = parser.parse_args()

    oauth_token = getpass.getpass("Paste the oauth_token cookie value (input hidden): ").strip()
    if not oauth_token:
        print("No token supplied.", file=sys.stderr)
        return 1
    if not oauth_token.startswith("oauth2_4/"):
        print(
            "Warning: that does not look like an oauth_token cookie "
            "(expected it to start with 'oauth2_4/'). Continuing anyway.",
            file=sys.stderr,
        )

    response = gpsoauth.exchange_token(args.email, oauth_token, args.android_id)
    master_token = response.get("Token")

    if not master_token:
        print("Exchange failed. Google returned:", file=sys.stderr)
        for key, value in response.items():
            print(f"  {key}: {value}", file=sys.stderr)
        print(
            "\nThe oauth_token is single-use and short-lived. Re-open EmbeddedSetup, "
            "grab a fresh cookie value, and try again.",
            file=sys.stderr,
        )
        return 1

    print("\nMaster token (store as GOOGLE_MASTER_TOKEN, treat as a password):\n")
    print(master_token)
    print(
        "\nkubectl create secret generic mealie-gkeep-sync \\\n"
        "  --from-literal=MEALIE_API_TOKEN='...' \\\n"
        f"  --from-literal=GOOGLE_MASTER_TOKEN='{master_token}'"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
