{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-state" (include "mealie-gkeep-sync.fullname" .) }}
  labels:
    {{- include "mealie-gkeep-sync.labels" . | nindent 4 }}
  {{- if or .Values.persistence.annotations .Values.persistence.retain }}
  annotations:
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.persistence.retain }}
    helm.sh/resource-policy: keep
    {{- end }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
